import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { ClientProviders } from "./layout.client";
import { Header } from "@/components/core/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`flex flex-col h-dvh w-full antialiased`}>
        <ClientProviders>
          <Header />
          <main className="flex-1 w-dvw gap-6 items-center justify-center px-4 md:px-0">
            <div className="w-full h-full mx-auto max-w-6xl">{children}</div>
          </main>
          <Toaster />
        </ClientProviders>
      </body>
    </html>
  );
}
